INSERT IGNORE INTO roles(name) VALUES('ROLE_USER');
INSERT IGNORE INTO roles(name) VALUES('ROLE_PROFESIONAL');
INSERT IGNORE INTO roles(name) VALUES('ROLE_EMPLOYEE');
INSERT IGNORE INTO roles(name) VALUES('ROLE_ADMIN');