INSERT IGNORE INTO roles(name) VALUES('ROLE_ADMIN');
INSERT IGNORE INTO roles(name) VALUES('ROLE_MODERATOR');
INSERT IGNORE INTO roles(name) VALUES('ROLE_EMPLOYEE');
INSERT IGNORE INTO roles(name) VALUES('ROLE_USER');