#CosmosCRM Master DataBase info

#Sirve para MasterDatabaseConfigProperties
multitenancy:
  cosmosmtapp:
    master:
      datasource:
        #url: jdbc:mysql://localhost:3306/master_db?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
        #driverClassName: com.mysql.cj.jdbc.Driver
        #username: root
        url: jdbc:postgresql://localhost:5432/master_db?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
        driverClassName: org.postgresql.Driver
        username: postgres
        password: 1234
        connectionTimeout: 20000
        maxPoolSize: 250
        idleTimeout: 300000
        minIdle: 5
        poolName: masterdb-connection-pool
      
      jpa:
        properties:
          hibernate:
            #spring.jpa.properties.hibernate.dialect
            dialect: org.hibernate.dialect.PostgreSQLDialect
