#CosmosCRM Master DataBase info

#Sirve para MasterDatabaseConfigProperties
multitenancy:
  cosmosmtapp:
    master:
      datasource:
        url: jdbc:mysql://localhost:3306/master_db?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
        username: root
        password: 1234
        driverClassName: com.mysql.cj.jdbc.Driver
        connectionTimeout: 20000
        maxPoolSize: 250
        idleTimeout: 300000
        minIdle: 5
        poolName: masterdb-connection-pool
